### ISSUE TITLE
java17-openj9	for 1.18.1

### ISSUE THREAD

**Issue by vorburger** [itzg/docker-minecraft-server#1234] opened 2021-12-29 00:02 UTC
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Just an issue to track evenually having a `java17-openj9` (we currently only have `java16-openj9`, note 16 vs 17) for Minecraft 1.18.1 (which requires Java 17 and does not work on Java 18 - apparently).

**Comment by itzg** [comment] 2022-01-01 17:02
Duplicate of #1209

**Closed by itzg** 2022-01-01 17:02 UTC
Labels: enhancement, status/needs triage

**Comment by itzg** [comment] 2022-01-01 18:28
`itzg/minecraft-server:java17-openj9` is now available.

**Comment by MennoGamed** [comment] 2022-01-02 00:55
Hey,
If i add the docker image to Pterodactyl the console will almost instand crach. 
Below are the logs of the console:

https://mcpaste.com/YCbbORZHygo09JGDxsfiT96B
