### ISSUE TITLE
Server isn't loading modpacks

### ISSUE THREAD

**Issue by vladbejenaru** [itzg/docker-minecraft-server#2412] opened 2023-10-06 15:33 UTC
### Discussed in https://github.com/itzg/docker-minecraft-server/discussions/2406

<div type='discussions-op-text'>

<sup>Originally posted by **vladbejenaru** October  2, 2023</sup>
Hi There, I try to make a minecraft server for my son and of course it should be a Forge server. He would like very much to have this modpack https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0/files active. I guess my issue is very similar with this one: https://github.com/itzg/docker-minecraft-server/issues/2314 but I cannot exactly point on what is not functioning... here is my compose file:

```
mcforge:
    image: itzg/minecraft-server
    container_name: mcforge
    ports:
      - 25566:25565
    environment:
      DEBUG: "TRUE"
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.20.1
      FORGE_VERSION: LATEST

      MODE: "creative"
      MOTD: "Sons Forge Server"
      MEMORY: "4G"
      GENERIC_PACK: "/modpacks/Guns-Nukes-And-Planes.zip"
    restart: unless-stopped
    volumes:
      - /virt/mcforge:/data
      - ./modpacks:/modpacks:ro
```

what I have also tried (variation):

```
    TYPE: "CURSEFORGE"
    TYPE: "AUTO_CURSEFORGE"
    MODE: "survival"#      CF_API_KEY: heresomerandomeapikeythatIhavedeletedhaha
    CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0"
    CF_MODPACK_ZIP: "/data/mods/Guns-Nukes-And-Planes.zip"
    USE_MODPACK_START_SCRIPT: "false"
    FTB_LEGACYJAVAFIXER: "true"
    CF_SERVER_MOD: Guns-Nukes-And-Planes.zip
    CF_SERVER_MOD: SkyFactory+4-4.2.4.zip
    MODPACK: Guns-Nukes-And-Planes.zip
    CF_SLUG: "guns-nukes-and-planes2-0"
    CURSEFORGE_FILES: |
       guns-nukes-and-planes2-0
```

Here are the logs:
[mcforge-logs.txt](https://github.com/itzg/docker-minecraft-server/files/12784418/mcforge-logs.txt)
</div>

**Comment by itzg** [comment] 2023-10-06 20:55
I'm sorry I hadn't gotten a chance to investigate your discussion item yet. Why do now believe it is an issue and not a discussion item? (Now there's twice the items for me to triage). And why do you think it is related to a closed/fixed issue yet you opened an issue?

**Comment by itzg** [comment] 2023-10-06 22:55
Closing duplicate of #2406 ...it got my attention though :)

**Closed by itzg** 2023-10-06 22:55 UTC
Labels: duplicate
