### ISSUE TITLE
Curl can't resolve host: Spigot 1.15.2

### ISSUE THREAD

**Issue by nose26** [itzg/docker-minecraft-server#498] opened 2020-04-18 21:31 UTC
I'm running docker-compose on a centos machine.  Whenever I attempt to run the container, it fails to download the .jar server file.  I am specifically having this issue with Spigot, but when I tried to use Paper it gave the same error.  When I set the server to custom, and specify a spigot.jar file, it runs, but gets hung up on loading libraries.  Because in this state it does not exit immediantly (as it does when it fails to download in the other two cases), I am able to open a shell and attempt to ping a few addresses, all of which fail.
  
This is my docker-compose file:
```
version: '3.3'
services:
    minecraft-server:
        image: itzg/minecraft-server:latest
        ports:
            - '80:80'
            - '25565:25565'
        volumes:
            - type: bind
              source: ./finServer/minecraft
              target: /data
        container_name: finServer
        environment:
            - EULA="true"
            - VERSION=1.15.2
            - TYPE=SPIGOT
            #- TYPE=CUSTOM
            #- CUSTOM_SERVER=/data/spigot-1.15.2.jar
            - MAX_MEMORY=4G
        command: --noconsole
```  
  
And this is the result:
```
Starting finServer ... done
Attaching to finServer
finServer           | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x   15 1000     1001          4096 Apr 18 21:00 /data'
finServer           | [init] Resolved version given 1.15.2 into 1.15.2
finServer           | [init] Resolving type given SPIGOT
finServer           | [init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.15.2.jar ...
finServer           | curl: (6) Could not resolve host: cdn.getbukkit.org
finServer exited with code 6

```
If I navigate to that url on a different machine, it downloads correctly.  
  
Meanwhile, the same issue occurs with Paper as well.  My docker-compose file in that situation:
```
version: '3.3'
services:
    minecraft-server:
        image: itzg/minecraft-server:latest
        ports:
            - '80:80'
            - '25565:25565'
        volumes:
            - type: bind
              source: ./finServer/minecraft
              target: /data
        container_name: finServer
        environment:
            - EULA=TRUE
            - VERSION=1.15.2
            - TYPE=PAPER
            #- TYPE=CUSTOM
            #- CUSTOM_SERVER=/data/spigot-1.15.2.jar
            - MAX_MEMORY=4G
        command: --noconsole

```  
And the output:  
```
Recreating finServer ... done
Attaching to finServer
finServer           | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1001            22 Apr 18 21:14 /data'
finServer           | [init] Resolved version given 1.15.2 into 1.15.2
finServer           | [init] Resolving type given PAPER
finServer           | [init] Downloading Paper 1.15.2 from https://papermc.io/api/v1/paper/1.15.2/latest/download ...
finServer           | curl: (6) Could not resolve host: papermc.io
finServer           | [init] ERROR: failed to download from https://papermc.io/api/v1/paper/1.15.2/latest/download (status=0)
finServer exited with code 3
```  
  
Once again, I can easily go to that url and download successfully.  I thought maybe using an already build spigot.jar file might help, so I tried using a custom server.  You'll note the commented out lines in the dockerfiles above.  This is the result when they are uncommented (and of course 'TYPE=SPIGOT' commented):  
```
Recreating finServer ... done
Attaching to finServer
finServer           | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1001            47 Apr 18 21:20 /data'
finServer           | [init] Resolved version given 1.15.2 into 1.15.2
finServer           | [init] Resolving type given CUSTOM
finServer           | [init] Using custom server jar at /data/spigot-1.15.2.jar ...
finServer           | [init] Creating server.properties in /data/server.properties
finServer           | [init] Setting server-name to 'Dedicated Server' in /data/server.properties
finServer           | [init] Skip setting server-ip
finServer           | [init] Setting server-port to '25565' in /data/server.properties
finServer           | [init] Setting motd to 'A Custom Minecraft Server powered by Docker' in /data/server.properties
finServer           | [init] Skip setting allow-nether
finServer           | [init] Skip setting announce-player-achievements
finServer           | [init] Skip setting enable-command-block
finServer           | [init] Skip setting spawn-animals
finServer           | [init] Skip setting spawn-monsters
finServer           | [init] Skip setting spawn-npcs
finServer           | [init] Skip setting spawn-protection
finServer           | [init] Skip setting generate-structures
finServer           | [init] Skip setting view-distance
finServer           | [init] Skip setting hardcore
finServer           | [init] Skip setting snooper-enabled
finServer           | [init] Skip setting max-build-height
finServer           | [init] Skip setting force-gamemode
finServer           | [init] Skip setting max-tick-time
finServer           | [init] Skip setting enable-query
finServer           | [init] Skip setting query.port
finServer           | [init] Setting enable-rcon to 'true' in /data/server.properties
finServer           | [init] Setting rcon.password to 'minecraft' in /data/server.properties
finServer           | [init] Setting rcon.port to '25575' in /data/server.properties
finServer           | [init] Skip setting max-players
finServer           | [init] Skip setting max-world-size
finServer           | [init] Setting level-name to 'world' in /data/server.properties
finServer           | [init] Skip setting level-seed
finServer           | [init] Setting pvp to 'true' in /data/server.properties
finServer           | [init] Skip setting generator-settings
finServer           | [init] Setting online-mode to 'true' in /data/server.properties
finServer           | [init] Skip setting allow-flight
finServer           | [init] Setting level-type to 'DEFAULT' in /data/server.properties
finServer           | [init] Skip setting resource-pack
finServer           | [init] Skip setting resource-pack-sha1
finServer           | [init] Skip setting player-idle-timeout
finServer           | [init] Setting difficulty to '1' in /data/server.properties
finServer           | [init] Creating log4j2.xml in /data/log4j2.xml
finServer           | [init] Checking for JSON files.
finServer           | [init] Setting initial memory to 1G and max to 4G
finServer           | [init] Starting the Minecraft server...
finServer           | *** Error, this build is outdated ***
finServer           | *** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
finServer           | *** Server will start in 20 seconds ***
finServer           | Loading libraries, please wait...

```
I guess maybe I just need to wait longer, but I have let various instances run for over 30 minutes, and one notable attempt ran overnight for close to 10 hours.  In any case, when I open a shell in the container, I can't seem to access the addresses listed in either of the other previous attempts.  Not sure what's going on here.

**Comment by itzg** [comment] 2020-04-18 23:48
Please make sure you have pulled the latest image. There was an issue fixed in the past few weeks that would cause the startup to "hang" at "Loading libraries"

**Comment by nose26** [comment] 2020-04-18 23:55
That was one of the first things I tried, yes.  I made sure I had the same issue (in all cases) after I had gotten the newest version: all the logs you see above were generated after making sure I had the newest version (I hope, unless I missed something).

**Comment by itzg** [comment] 2020-04-19 18:31
Since several domains are failing to resolve, it sounds like a DNS issue with your particular Docker setup. You'll need to search around for general docker advise such as posts like https://forums.docker.com/t/dns-resolution-not-working-in-containers/36246

Along with that information, you can troubleshoot against this specific image by starting with just bash:

```
docker run -it --rm --entrypoint bash itzg/minecraft-server
```

From there you can inspect things like the resolv conf or run nslookup, such as
```
bash-4.4# nslookup papermc.io
nslookup: can't resolve '(null)': Name does not resolve

Name:      papermc.io
Address 1: 104.26.2.2
Address 2: 104.26.3.2
Address 3: 2606:4700:20::681a:202
Address 4: 2606:4700:20::681a:302
bash-4.4# cat /etc/resolv.conf
# This configuration is written to the config.iso
nameserver 192.168.65.1
```

For comparison, that DNS server IP is my home network router.

**Comment by Dynamic-Gravity** [comment] 2020-04-19 20:31
@itzg  the actual issue is `firewalld` blocking the Docker networking from resolving DNS. 
See this [post](https://serverfault.com/questions/1002482/centos8-podman-with-enabled-firewalld-breaks-dns-for-container).

Note: I am using CentOS 8.1

I had the same issue as the OP and disabled `firewalld` temporarily and then the issue was resolved. So we need to figure out how to add the docker networking to a trusted zone on the host and then DNS should work again from within the container.

Here is an example of my configuration:

```bash
sudo podman run -d \
-v /mnt/tank/minecraft/paper-test:/data:Z \
-e EULA=TRUE -e TYPE=PAPER -e VERSION=1.15.2 \
-p 25565:25565 \
--name mc-paper-test itzg/minecraft-server:adopt11 \
--noconsole
```

**Comment by itzg** [comment] 2020-04-20 03:15
I’m going to close this issue since it doesn’t seem to be anything caused by or unique to this image. Maybe you’ll find some things that help in this issue or the Redhat issue mentioned there

https://github.com/moby/moby/issues/16137

**Closed by itzg** 2020-04-20 03:15 UTC
Labels: status/waiting on feedback

**Comment by enric1994** [comment] 2020-05-24 12:15
What about using`network_mode: "host"` in `docker-compose.yaml`?
