### ISSUE TITLE
Deploy images to GitHub container registry

### ISSUE THREAD

**Issue by eaglesemanation** [itzg/docker-minecraft-server#2009] opened 2023-03-16 06:30 UTC
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Docker recently announced that they will sunset free team accounts in their container registry. While this does not affect your containers, I think it would be helpful to have a backup registry. There is an example of how this can be done: https://github.com/skills/publish-packages
I'm a bit busy now, but I may work on this on weekend and submit a PR for that

**Comment by itzg** [comment] 2023-03-16 12:24
This seems to be a duplicate of #1444

**Comment by itzg** [comment] 2023-04-24 19:56
Images now available on GHCR: https://github.com/itzg/docker-minecraft-server/pkgs/container/minecraft-server

**Closed by itzg** 2023-04-24 19:56 UTC
Labels: enhancement
