### ISSUE TITLE
Outdated java version reported by paper (warning only)

### ISSUE THREAD

**Issue by rwarren** [itzg/docker-minecraft-server#765] opened 2021-02-12 01:25 UTC
I just started a paper minecraft server and it is reporting an outdated java version:

```
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 11. When Paper for Minecraft 1.17 is
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 11 will
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 1.8.0_212
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information:
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java11
mc3    | [01:18:49 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
```

**Comment by itzg** [comment] 2021-02-12 13:40
You probably need to re-pull the latest image since I have already updated to Java 11

https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version

**Comment by itzg** [comment] 2021-02-12 13:42
I'll go ahead and close since it is also a duplicate of https://github.com/itzg/docker-minecraft-server/issues/676

**Closed** 2021-02-12 13:42 UTC
Labels: status/waiting on feedback
