### ISSUE TITLE
After Update Docker starts only with  privileged: true

### ISSUE THREAD

**Issue by Powerbolt1989** [itzg/docker-minecraft-server#755] opened 2021-02-07 19:44 UTC
After rebuild today my Server starts only with privileged: true. 

Without i get the error message 

sleep: cannot read realtime clock: Operation not permitted

curl: (28) Resolving timed out after 1225600658137 milliseconds

sleep: cannot read realtime clock: Operation not permitted

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsr-x+ 8 1000 1000 4096 Jan 29  2021 /data'

curl: (28) Timeout was reached

[init] Resolved version given LATEST into 

[init] Autopause functionality enabled

[init] Resolving type given SPIGOT

sleep: cannot read realtime clock: Operation not permitted

System is the Rasperry Pi 4 with 8 GB

What could i do to fix this Problem?

thx
Powerbolt

**Comment by Powerbolt1989** [comment] 2021-02-07 19:46
version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:multiarch-latest
#    image: itzg/minecraft-server:2021.1.0-multiarch-latest
    ports:
      - "25565:25565"
    volumes:
      - "/srv/dev-disk-by-label-WD10a/minecraft/mcgame:/data"
    environment:
      TZ: Europe/Berlin
      EULA: "TRUE"
      ENABLE_RCON: "false"
      TYPE: SPIGOT
      MEMORY: 2700m
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_EST: "200"
      AUTOPAUSE_TIMEOUT_INIT: "200"
    restart: unless-stopped
    container_name: MinecraftServer
    tty: true
    stdin_open: true
#    privileged: true
My Compose File

**Comment by itzg** [comment] 2021-02-07 23:31
That fix seems fairly logical. I think I only have a RPI 3B+ and will need to revive it. Can you try some of the slightly older tags to see if you can narrow where it might have changed. It's probably a change in the base image.

**Comment by Powerbolt1989** [comment] 2021-02-08 20:38
Mhm, 
tried the now 4 older builds. Same error. I updatet Docker itself too. Maybe here are some changes?

**Comment by itzg** [comment] 2021-02-08 20:42
Oh, if you updated Docker recently then that's more likely the cause.

**Comment by Powerbolt1989** [comment] 2021-02-08 20:45
6 Docker Compose are now running on the pi. The only one who makes this Problem ist the Minecraft Image. It runs perfect with the privilige Mode but i dont want it to run in this mode.

**Comment by itzg** [comment] 2021-02-08 21:38
I agree that I wouldn't want to enable privileged mode; however, I'm running out of ideas :( Since `sleep` is a very basic command and only used by the autopause code, you can stop using autopause feature. Are any of your other containers calling `sleep` successfully?

**Comment by Powerbolt1989** [comment] 2021-02-09 19:39
I dont have any other containers with sleep. But without Autopause i get errors.

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsr-x+ 8 1000 1000 4096 Jan 29  2021 /data'

curl: (28) Timeout was reached

[init] Resolved version given LATEST into 

[init] Resolving type given SPIGOT

[init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.16.5.jar ...

curl: (28) Timeout was reached

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsr-x+ 8 1000 1000 4096 Jan 29  2021 /data'

**Comment by itzg** [comment] 2021-02-09 19:42
It's strange that disabling auto-pause caused a difference in behavior early in startup. In any case, I'm afraid you're now hitting this other issue

https://github.com/itzg/docker-minecraft-server/issues/756

...and I'm stuck wondering what the upstream image has done to break `curl`.

**Comment by BC6B** [comment] 2021-02-10 04:37
Just did a fresh install of Docker and ran into this exact same issue. Any idea which version broke this? I might try to downgrade.

**Comment by Powerbolt1989** [comment] 2021-02-10 08:23
I install itzg Minecraft Server on January 18th. I think i updated Docker 2-3 Days before @BC6B. So The Versions before 18th January must work.

**Comment by BC6B** [comment] 2021-02-10 15:53
I ended up downgrading Docker to 19.03.15 last night but ran into the same timeout. I will try to go back further tonight.

**Comment by itzg** [comment] 2021-02-10 19:41
Maybe there was a kernel update that influenced this. What distro is everyone here running on rpi? Raspbian?

**Comment by Powerbolt1989** [comment] 2021-02-12 12:18
Yes for me it is Raspian 32 Bit

**Comment by Powerbolt1989** [comment] 2021-02-18 20:29
Yeah @itzg I found the Solution. We need to Upgrade the libseccomp on RP4.

http://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb

Link this to the other Tickets. It fixed also the Autopause.

Have a great Day Powerbolt

**Comment by itzg** [comment] 2021-02-20 22:34
Good to close the issue then?

**Closed** 2021-02-20 22:35 UTC
Labels: platform/rpi

**Comment by RobieOne** [comment] 2021-02-21 05:29
Upgrading libseccomp worked for me... Thanks Powerbolt1989!

**Comment by xcellardoor** [comment] 2021-03-07 11:42
Hi Everyone,

A friend recently helped me out with this, and I thought it may be helpful to post the (very simple) workaround here for anyone to find in the future.

It turns out Docker has a special flag for shared-volumes, the 'Z' flag. There is also the lower-case 'z' flag though they do different things. See: https://stackoverflow.com/a/35222815 and https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label 

I'm not 100% sure of the technical ins and outs as my RasPi4 doesn't run SELinux though it does appear to have an AppArmor module running. Either way, setting my persistent data volume to use this 'Z' flag solved all problems immediately, e.g:
 
 minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server:multiarch-latest
    volumes:
      - "/srv/volumes/minecraft_server:/data:Z"

Sorry for necro-bumping, but hope this helps someone out who may still be struggling when the solutions above didn't work, as was my case.

**Comment by itzg** [comment] 2021-03-07 13:25
Great info @xcellardoor ! I could add a note about that in the README.

**Comment by itzg** [comment] 2021-03-29 11:57
Just found official description of the seccomp solution is mentioned here https://docs.docker.com/engine/security/seccomp/
