### ISSUE TITLE
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by captainchapster** [itzg/docker-minecraft-server#3086] opened 2024-10-01 12:44 UTC
### Describe the problem

Docker container continuously restarts (judging from monitoring docker ps). Logs show the subject mentioned error whilst trying to download the latest version of the server from minecraft.

### Container definition

docker run -d -it --name mcbedrockserver --restart=unless-stopped -e EULA=TRUE -e SERVER_PORT=19132 -p 19132:19132/udp -v /home/alex/mc-br-docker:/data itzg/minecraft-bedrock-server

### Container logs

DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=1000 from match path
DEBU[0000] Resolved GID=1000 from match path
Looking up latest version...
Downloading Bedrock server version 1.21.31.04 ...
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
ERROR failed to download from https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.31.04.zip
      Double check that the given VERSION is valid

**Comment by itzg** [comment] 2024-10-01 12:51
This is posted in the wrong repo and is a duplicate of a fixed issue https://github.com/itzg/docker-minecraft-bedrock-server/issues/458

Re-pull your image to apply the fix.

**Closed** 2024-10-01 12:52 UTC
Labels: bug, duplicate

**Comment by monsieurgui** [comment] 2025-07-10 23:45
I'm still getting the issue as of today. @itzg
