### ISSUE TITLE
java updated version coming?

### ISSUE THREAD

**Issue by finndo77** [itzg/docker-minecraft-server#690] opened 2020-12-15 16:24 UTC
Hi,
just checking in to see if you plan on updating the java version in the minecraft-server docker image.

[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 11. When Paper for Minecraft 1.17 is
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 11 will
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 1.8.0_212
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information: 
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java11
[11:19:03 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************

**Comment by finndo77** [comment] 2020-12-15 16:25
I am not sure if this conflicts with any other part of the image though, as everything I have read says to use 1.8...

**Comment by itzg** [comment] 2020-12-15 18:31
Duplicate of #676 but in the meantime, can always use the image tag `itzg/minecraft-server:adopt11`

**Closed by itzg** 2020-12-15 18:31 UTC
