### ISSUE TITLE
/start-deployFTBA: line 53: ${ftbInstallMarker}: ambiguous redirect

### ISSUE THREAD

**Issue by mmastrocinque** [itzg/docker-minecraft-server#672] opened 2020-11-26 04:45 UTC
I've made some dns changes and reinstalled ubuntu and now no longer have the issue. New issue has occured though, should I make a new issue? 

```
...
MESSAGE: Trying unpacked library net.sf.trove4j:trove4j:3.0.3
MESSAGE: Considering library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Downloading library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Trying unpacked library org.apache.maven:maven-artifact:3.5.3
Extracting: /forge-1.12.2-14.23.5.2846-universal.jar
To:          /data/./forge-1.12.2-14.23.5.2846-universal.jar
The server installed successfully, you should now be able to run the file forge-1.12.2-14.23.5.2846-universal.jar
You can delete this installer file now if you wish
=================  FORGE INSTALL ENDS  =================
Pack install Finished.
/start-deployFTBA: line 53: ${ftbInstallMarker}: ambiguous redirect
```

_Originally posted by @mmastrocinque in https://github.com/itzg/docker-minecraft-server/issues/645#issuecomment-734068630_

**Comment by itzg** [comment] 2020-11-26 14:41
Thanks for creating a new issue foe this one. I'll look into it.

**Comment by itzg** [comment] 2020-11-26 14:48
Duplicate of #671

**Closed by itzg** 2020-11-26 14:48 UTC
