### ISSUE TITLE
Update ARM Builds for Minecraft

### ISSUE THREAD

**Issue by nikhiljha** [itzg/docker-minecraft-server#316] opened 2019-05-05 02:57 UTC
I know this has been brought up before, but it looks like the `raspberrypi` tag isn't updated anymore. There are some really powerful ARM SBCs capable of running lots of Minecraft servers, and this image seems really well thought out. It would be nice if it was supported again.

**Comment by nikhiljha** [comment] 2019-05-05 03:11
I just tried to build the `Dockerfile` in `master` on my Odroid N2 and it built just fine. The images just need to be build on Docker Hub and this is already perfect :)

I uploaded it here for now: https://hub.docker.com/r/njha/minecraft

**Comment by nikhiljha** [comment] 2019-05-05 03:17
Actually just kidding, the 3 binaries: restify, rcon-cli, and mc-server-runner don't have aarch64 either. Gah.

**Comment by nikhiljha** [comment] 2019-05-05 03:36
Okay I got it to work. Here's what needs to be done.

1. Add "arm64" to targets in goreleaser for all three projects. (Can I suggest replacing "arm" with "arm64"? I don't think there are many (if any) non-arm64 ARM CPUs capable of running a Minecraft server that well anyway...)
2. Build and release.
3. ???
4. Profit.

**Comment by itzg** [comment] 2019-05-05 13:38
@nikhiljha thanks for doing the research on arm64 viability. Yeah, running the server on raspberrypi has proven to be pretty much unusable; however, I'll add the arm64 build rather than replace just so I can keep that option open. (Besides raspberrypi is what I have on my desk here to test with :) )

I'm going to keep a checklist here as I update the dependencies:

- [ ] restify
- [ ] rcon-cli
- [ ] mc-server-runner

**Comment by nikhiljha** [comment] 2019-05-05 15:35
<img width="787" alt="Screen Shot 2019-05-05 at 8 35 00 AM" src="https://user-images.githubusercontent.com/2773700/57196313-adf22c00-6f10-11e9-8b84-19c75a214931.png">

It works! Deployed in docker swarm as usual with no issues.

**Comment by itzg** [comment] 2019-05-05 15:39
Now my remaining challenge is blending the balena (formerly resin) cross-build support into the Dockerfile since Docker Hub builds via x86.

**Comment by itzg** [comment] 2019-05-05 16:29
@nikhiljha can you now test out the newly tagged image `itzg/minecraft-server:aarch64` ?

**Comment by nikhiljha** [comment] 2019-05-05 16:35
It doesn't seem to actually be `aarch64`? 

```
no suitable node (unsupported platform on 2 nodes)
```

**Comment by itzg** [comment] 2019-05-05 16:40
Well, the base image is definitely aarch64, but I’ll do some experimenting with my raspberry pi with a similar base image from balena

**Comment by nikhiljha** [comment] 2019-05-05 16:43
FWIW all I had to do to get it to build (from an aarch64 platform, so not as hard as cross-compiling for sure) was `docker build https://github.com/itzg/dockerfiles.git#master:minecraft-server --build-arg ARCH=arm64`.

Resulting image is at `njha/minecraft:arm`

**Comment by itzg** [comment] 2019-05-05 19:27
I discovered manifest lists are a way to explicitly associate tags with their respective architecture. Can you now try `itzg/minecraft-server:multiarch` on your arm64 system? I also fixed `ARCH` in the tag `aarch64` that is referenced by the manifest.

**Comment by nikhiljha** [comment] 2019-05-05 20:59
```
/start-minecraftFinalSetup: line 119: /usr/local/bin/mc-server-runner: No error information,
/start-minecraftFinalSetup: line 119: /usr/local/bin/mc-server-runner: cannot execute binary file: Exec format error
```

The image is correct but the binaries are wrong.

**Comment by itzg** [comment] 2019-05-05 22:00
Can you try one more time @nikhiljha ? I re-pushed the multiarch label/manifest with the proper aarch64 sha.

**Comment by nikhiljha** [comment] 2019-05-06 04:26
```
# A fatal error has been detected by the Java Runtime Environment:,
#,
#  Internal Error (assembler_aarch64.hpp:1156), pid=38, tid=0x0000007f7d747aa0,
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction,
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04),
# Derivative: IcedTea 3.12.0,
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops),
# Distribution: Custom build (Sat May  4 17:44:26 UTC 2019),
# Core dump written. Default location: /data/core or core.38,
# An error report file with more information is saved as:,
# /data/hs_err_pid38.log
```

File: [/data/hs_err_pid38.log](https://pastebin.com/Q2L4i8fM)

Still no :( It starts the Minecraft server and then this immediately happens. I'm pretty sure it's not a Minecraft/Paper issue because the image I built from this dockerfile works fine.

I can try with another aarch64 board at some point but...

**Comment by itzg** [comment] 2019-05-07 20:41
Thanks for trying that out (again). There must be something different about the base openjdk image for aarch64 on alpine than me using the alpine image as the base and then adding the openjdk package. Maybe this is an excuse for me to buy an Odroid N2 board :)

**Comment by itzg** [comment] 2019-05-07 20:41
...for now, I'll gladly point people to the image you pushed

**Comment by shaun-blake** [comment] 2019-05-09 19:37
Just to add a little here. I was looking into an easy way to get a minecraft server on my Raspberry Pi 3 Model B+ which has docker running.

I tried building like @nikhiljha with:
```
docker build https://github.com/itzg/dockerfiles.git#master:minecraft-server --build-arg ARCH=arm64 --tag minecraft-server
```
The build succeeds, but when I try to run, it gives an error:
```
docker run --rm -p 25565:25565 -e EULA=true --name mc minecraft-server
...
/start-minecraftFinalSetup: line 119: /usr/local/bin/mc-server-runner: cannot execute binary file: Exec format error
/start-minecraftFinalSetup: line 119: /usr/local/bin/mc-server-runner: No error information
```

Also, if I try to run the image built by @nikhiljha I get this:
```
docker run --rm -p 25565:25565 -e EULA=true --name mc njha/minecraft:arm
Unable to find image 'njha/minecraft:arm' locally
arm: Pulling from njha/minecraft
...
Digest: sha256:aaec8b9402999acfa9ac914d0ee3ce0f3141716b8aa1d689c40d0d4c56769a62
Status: Downloaded newer image for njha/minecraft:arm
standard_init_linux.go:207: exec user process caused "exec format error"
```

**Comment by itzg** [comment] 2019-05-09 21:44
The special label “multiarch” now contains RaspberryPi 3 support...but I gave up after an hour of waiting for the server itself to generate the initial spawn area :(

**Comment by itzg** [comment] 2019-05-09 23:12
...to clarify the tagged image is `itzg/minecraft-server:multiarch`, but the arm64 reference isn't working yet.

**Comment by nikhiljha** [comment] 2019-05-09 23:28
@shaun-blake I suspect you're running an `armhf` image instead of an `aarch64` (also known as `arm64`) image on your Raspberry Pi. The Pi 3 CPU *does* support arm64 but the default image that you get on raspberrypi.org is armhf.

**Comment by shaun-blake** [comment] 2019-05-10 01:50
Thanks to both of you, @itzg and @nikhiljha. That explains why my previous attempts didn't work. The `multiarch` tag did work for me, it just took too long. I didn't actually get it started.  I gave it a few hours and it never logged anything past:

> [22:07:12] [Server thread/INFO]: Reloading ResourceManager: Default

The `docker stats` showed the cpu usage at around 300% constantly so I'm going to guess it just doesn't have resources to run it. I guess I'll have to run it on something else.

**Comment by jalu14** [comment] 2019-05-16 21:27
> Thanks to both of you, @itzg and @nikhiljha. That explains why my previous attempts didn't work. The `multiarch` tag did work for me, it just took too long. I didn't actually get it started. I gave it a few hours and it never logged anything past:
> 
> > [22:07:12] [Server thread/INFO]: Reloading ResourceManager: Default
> 
> The `docker stats` showed the cpu usage at around 300% constantly so I'm going to guess it just doesn't have resources to run it. I guess I'll have to run it on something else.

Latest minecraft server (1.14 and 1.14.1) lag very hard on any device, just running on a scaleway server with 100% utilization with no users on, is on Minecraft side not on this repo's

**Comment by nikhiljha** [comment] 2019-05-19 02:32
Updated `njha/minecraft:arm` to work with 1.14.1 Paper. (Built the latest version of this repository.)

**Comment by tengshan2008** [comment] 2019-12-25 03:43
Still not work on Raspberry Pi. ver: 1.15.1

My device is Raspberry Pi 4, use the tag 'rpi3', but stuck on `Reloading ResourceManager: Default`,
when I run it with normal shell, it is ok. I guess maybe armhf problem, but I don't kown how to build a new image,

**Comment by itzg** [comment] 2019-12-27 02:26
@tengshan2008 my apologies, I am still waiting for the new docker build mechanism to make it easier to create multi-architecture images. 

For now, to build the image on your Raspberry Pi, make sure you have git and docker installed and run:

```
git clone https://github.com/itzg/docker-minecraft-server.git
cd docker-minecraft-server
docker build -t itzg/minecraft-server .
```

**Comment by tengshan2008** [comment] 2019-12-31 03:04
Raspberry Pi 4

I follow your steps build new image, but it is failed, when I change AACH to armv7, build success.

Run this new image, it still stuck on `Reloading ResourceManager: Default`, and CPU used 300%.

By the way. When I changed memory, max is 2000M, I can't set over 2G.

Waiting for you plan for raspberry pi.

**Comment by itzg** [comment] 2019-12-31 04:09
@tengshan2008 I’m so sorry, I forgot about the ARCH build arg needing to be altered. Skimming back through some of the previous comments on this issue I think you’re running into similar hardware/OS distro limitations as others.

**Comment by BKoster98** [comment] 2020-02-28 02:22
Hello, I am also attempting to get this running on a Raspberry Pi 4.  I tried the above, cloning the repository and building the docker image.  However, I am unsuccessful and continue running into this error during the build.
`Step 13/25 : RUN easy-add --var os=${TARGETOS} --var arch=${TARGETARCH}${TARGETVARIANT}   --var version=1.2.0 --var app=restify --file restify   --from https://github.com/itzg/{{.app}}/releases/download/{{.version}}/{{.app}}_{{.version}}_{{.os}}_{{.arch}}.tar.gz
 ---> Running in f2bace4cc54a
/usr/bin/easy-add: line 1: syntax error: unterminated quoted string`

The command I am running is 
`docker build -t itzg/minecraft-server .`
and I've even tried
`docker build -t itzg/minecraft-server --build-arg ARCH=armv7 .`

Am I doing something incorrectly (I am new to docker, so this is very possible)?

**Comment by itzg** [comment] 2020-02-28 14:40
Ah, I forgot to update this issue with a few important details on the multi-architecture front:
- The Dockerfile now uses [BuildKit compliant](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope) build args: TARGETOS, TARGETARCH, and TARGETVARIANT which would have the values "linux", "arm", and "v7" respectively for RaspberryPi
- There is now a [multiarch](https://github.com/itzg/docker-minecraft-server/tree/multiarch) branch which uses a Debian/AdoptOpenJDK base image to leverage the very latest Java 8. I found issues on aarch64 that required that newer JVM
- There is already an tagged image `itzg/minecraft-server:multiarch` which is fully multi-arch supported and will run as-is on RaspberryPi, aarch64 based systems, and regular x64

...however, I found that only very old versions of the server (about 1.7 ish) perform acceptably on RaspberryPi. Apparently the server code is just not optimized for that platform :(

**Comment by BChip** [comment] 2020-04-29 21:27
I can confirm `itzg/minecraft-server:multiarch` works on `Linux pinebookpro 5.6.0-2-MANJARO-ARM #1 SMP Thu Apr 2 21:13:13 CEST 2020 aarch64 GNU/Linux` flawlessly.

**Comment by fnord123** [comment] 2020-05-20 00:49
I was able to get itzg/minecraft-server:armv7 running on my Raspberry Pi 4, but not itzg/minecraft-server:multiarch, nor itzg/minecraft-server:aarch64

For reference, I am running the latest Raspbian 64 bit builds. 

Uname from inside the pod: 
root@minecraft-c99554dc9-dnvsq:/data# uname -a
Linux minecraft-c99554dc9-dnvsq 5.4.40-v8+ #1316 SMP PREEMPT Tue May 12 13:17:34 BST 2020 aarch64 aarch64 aarch64 GNU/Linux
Uname from the node:
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.40-v8+ #1316 SMP PREEMPT Tue May 12 13:17:34 BST 2020 aarch64 GNU/Linux
 
The multiarch build consistently gives "exec format error":
pi@Lenovo-Laptop:~$ kubectl logs -n minecraft minecraft-795dd97bc-grjs8
standard_init_linux.go:211: exec user process caused "exec format error"
pi@Lenovo-Laptop:~$ kubectl describe -n minecraft pod minecraft-795dd97bc-grjs8 | grep image
  Normal   Pulled     13s (x4 over 56s)  kubelet, kslave2   Container image "itzg/minecraft-server:multiarch" already present on machine

The aarch64 consistently crashes the JVM after a little while:
pi@Lenovo-Laptop:~$ kubectl logs -f -n minecraft minecraft-7656fd55d7-ssbdn
usermod: no changes
Changing ownership of /data to 1000 ...
chown: /data/server.properties: Read-only file system
chown: /data/permissions.json: Read-only file system
chown: /data/whitelist.json: Read-only file system
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwt    2 1000     1000           120 May 20 00:45 /data'
Checking version information.
Checking type information.
Downloading minecraft_server.1.15.2.jar ...
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
...
[00:46:40] [Server thread/INFO]: Loaded 6 recipes
[00:46:43] [Server thread/INFO]: Loaded 825 advancements
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=50, tid=0x0000007f7040aab0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Thu May  9 18:09:31 UTC 2019)
# Core dump written. Default location: /data/core or core.50

Any ideas? Not sure what I'm doing wrong..

**Comment by nikhiljha** [comment] 2020-05-20 03:48
The aarch64 crash seems similar to https://github.com/itzg/docker-minecraft-server/issues/316#issuecomment-489497213.

**Comment by fnord123** [comment] 2020-05-20 14:39
> The aarch64 crash seems similar to [#316 (comment)](https://github.com/itzg/docker-minecraft-server/issues/316#issuecomment-489497213).

I agree.  It seems there are two different issues potentially:
- The multi arch build is either incorrect, or not being interpreted correctly on certain environments (e.g. my environment k3s/RPi4/Raspbian)
- The aarch64 build crashing on k3s/raspbian/raspberry pi 4 (my environment and @nikhiljha )

Not sure if the maintainer prefers forking into two issues so leaving it here for now :)

**Comment by pschonmann** [comment] 2020-05-20 21:50
Same problem Here, Running from Portainer on Coreelec / Odroid N2

```usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    7 1000     1000          1024 May 20 21:22 /data'
Checking version information.
ecking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
[21:25:08] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:25:08] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:25:08] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:25:08] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:25:08] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:25:09] [Server thread/INFO]: Starting minecraft server version 1.15.2
[21:25:09] [Server thread/INFO]: Loading properties
[21:25:09] [Server thread/INFO]: Default game type: SURVIVAL
[21:25:09] [Server thread/INFO]: Generating keypair
[21:25:09] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:25:10] [Server thread/INFO]: Using default channel type
[21:25:11] [Server thread/INFO]: Preparing level "world"
[21:25:11] [Server thread/INFO]: Found new data pack vanilla, loading it automatically
[21:25:11] [Server thread/INFO]: Reloading ResourceManager: Default
[21:25:17] [Server thread/INFO]: Loaded 6 recipes
[21:25:19] [Server thread/INFO]: Loaded 825 advancements
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=40, tid=0x0000007f98a48ab0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Thu May  9 18:09:31 UTC 2019)
# Core dump written. Default location: /data/core or core.40
#
# An error report file with more information is saved as:
# /data/hs_err_pid40.log
#
# Compiler replay data is saved as:
# /data/replay_pid40.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
2020/05/20 21:25:25 Done```

**Comment by nikhiljha** [comment] 2020-05-20 22:13
@pschonmann Oh hey, another person using an ODroid N2 :)

Apparently this is because the image is using an older version of the openjdk image...
```Dockerfile
FROM openjdk:8u212-jre-alpine
```

This issue https://github.com/openhab/openhab-docker/issues/233 is running the same version of openjdk and is apparently fixed in newer releases. I've switched to x86_64 for Minecraft (since I now need to handle 40+ players) so I can't test atm.

Can you give rebuilding the image with a newer version a shot? Just replace the line above with

```Dockerfile
FROM openjdk:8u252-jre-alpine
```

Also, I'm using OpenJ9 now instead of Hotspot. The object cache does wonders for performance (at the cost of some disk space). Might be worth looking into switching to the j9 docker image :)

**Comment by nikhiljha** [comment] 2020-05-20 22:20
Gah, https://github.com/itzg/docker-minecraft-server/pull/536#issuecomment-631758474

**Comment by itzg** [comment] 2020-05-21 12:16
Yeah, I should at least make the same base image switch I did for armv7 in the aarch64 branch too.

**Comment by itzg** [comment] 2020-05-21 12:16
Oops, didn’t notice your PR yet. Looking at that instead...

**Comment by itzg** [comment] 2020-05-22 01:55
The latest `itzg/minecraft-server:multiarch` image tag is now using Java 1.8.0_252 for arm64 (aka aarch64), armv7 (aka 32-bit RaspberryPi 3 B+ and newer), and amd64 (aka good ol' 64-bit Intel/AMD). 

FYI it is now maintained in the [multiarch branch](https://github.com/itzg/docker-minecraft-server/tree/multiarch) and built for all three platforms using buildx/BuildKit.

**Comment by itzg** [comment] 2020-05-22 01:56
@pschonmann, can you re-pull the multiarch tag and see if that fixes your Odroid N2 setup? I have verified on an AWS EC2 a1.medium instance.

**Comment by pschonmann** [comment] 2020-05-22 07:44
Yeap, its working

**Comment by itzg** [comment] 2020-05-22 14:14
I am going to close this issue since I feel very satisfied that the multiarch branch along with buildx/BuildKit builds finally produces usable images on all three processor architectures.

**Closed by itzg** 2020-05-22 14:14 UTC
