### ISSUE TITLE
Forge crash related to GUI, even with GUI=FALSE

### ISSUE THREAD

**Issue by OverclockedSanic** [itzg/docker-minecraft-server#799] opened 2021-03-11 21:05 UTC
A quick workaround is to just set it as a custom server instead and point to the JAR directly.

Log:

    [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x   14 1000     1000            31 Mar 11 20:52 /data'
    [init] Resolved version given 1.16.5 into 1.16.5
    [init] Resolving type given FORGE
    [init] server.properties already created, skipping
    [init] log4j2.xml already created, skipping
    [init] Checking for JSON files.
    [init] Setting initial memory to 1G and max to 1G
    [init] Starting the Minecraft server...
    JVM info: IcedTea - 1.8.0_212 - 25.275-b01
    java.net.preferIPv4Stack=true
    Found java version 1.8.0_212
    Exception in thread "main" 
    java.awt.HeadlessException: 
    No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	    at java.awt.Window.<init>(Window.java:536)
	    at java.awt.Frame.<init>(Frame.java:420)
	    at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:408)
	    at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:170)
	    at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:143)

**Comment by itzg** [comment] 2021-03-11 21:19
I can't reproduce this issue. I tried the following and all started up fine:

```
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE -e GUI=false itzg/minecraft-server
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE -e GUI=false itzg/minecraft-server:java8
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE itzg/minecraft-server
```

Please make sure you have pulled the latest image. You can also add `-e DEBUG_EXEC=true` to output the final command executed.

**Comment by OverclockedSanic** [comment] 2021-03-11 21:28
Weird. I'm using docker-compose, here's the part related to forge:

    minecraft-forge:
            container_name: minecraft-forge
            image: itzg/minecraft-server:java8
            restart: unless-stopped
            ports:
                - 25569:25565/tcp
            networks:
                - bungeecord_forge
            volumes:
                - './minecraft/forge:/data'
            environment:
                GUI: 'FALSE'
                EULA: 'TRUE'
                #TYPE: 'CUSTOM'
                #CUSTOM_SERVER: 'forge-1.16.5-36.0.43.jar'
                TYPE: 'FORGE'
                VERSION: '1.16.5'
                FORGEVERSION: '36.0.43'
                FORGE_INSTALLER: 'forge-installer.jar'

**Comment by itzg** [comment] 2021-03-11 21:31
Still works fine for me with:

```
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE -e FORGEVERSION=36.0.43 itzg/minecraft-server:java8
```

Why are you specifying `FORGE_INSTALLER` though? I can't confirm that variant since I don't know what copy of the file you're using there.

**Comment by OverclockedSanic** [comment] 2021-03-11 21:37
Oh, this makes a ton of sense. The server itself is not starting with a GUI, as this is the output with `DEBUG_EXEC`:

  + exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-installer.jar nogui
  
  But specifying `FORGE_INSTALLER` seems to be running the installer with GUI. Removing `FORGE_INSTALLER` fixes it, although imo we should still look what's happening if we *do* specify it. It's just the `forge-1.16.5-36.0.43.jar` from the official site, renamed for convenience.

**Comment by itzg** [comment] 2021-03-11 21:41
I'm confused now. Your DEBUG_EXEC output doesn't match your compose file. It looks like you used:

```yaml
CUSTOM_SERVER: forge-installer.jar
```

where you can't run the forge installer as the server jar.

**Comment by OverclockedSanic** [comment] 2021-03-11 21:44
I saved this in my `docker-compose.yml`:

    minecraft-forge:
            container_name: minecraft-forge
            image: itzg/minecraft-server:java8
            restart: unless-stopped
            ports:
                - 25569:25565/tcp
            networks:
                - bungeecord_forge
            volumes:
                - './minecraft/forge:/data'
            environment:
                EULA: 'TRUE'
                #TYPE: 'CUSTOM'
                #CUSTOM_SERVER: 'forge-1.16.5-36.0.43.jar'
                #GUI: 'FALSE'
                TYPE: 'FORGE'
                VERSION: '1.16.5'
                FORGEVERSION: '36.0.43'
                FORGE_INSTALLER: 'forge-installer.jar'
                DEBUG_EXEC: 'TRUE'
                
                
ran `docker-compose up -d` (in the same directory)
and got this by running `docker logs minecraft-forge`:

    [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x   14 1000     1000            33 Mar 11 21:41 /data'
    [init] Resolved version given 1.16.5 into 1.16.5
    [init] Resolving type given FORGE
    [init] server.properties already created, skipping
    [init] log4j2.xml already created, skipping
    [init] Checking for JSON files.
    [init] Setting initial memory to 1G and max to 1G
    [init] Starting the Minecraft server...
    + exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-installer.jar
    JVM info: IcedTea - 1.8.0_212 - 25.275-b01
    java.net.preferIPv4Stack=true
    Found java version 1.8.0_212
    Exception in thread "main" 
    java.awt.HeadlessException: 
    No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	    at java.awt.Window.<init>(Window.java:536)
	    at java.awt.Frame.<init>(Frame.java:420)
	    at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:408)
	    at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:170)
	    at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:143)
    2021-03-11T21:42:04.098Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
    2021-03-11T21:42:04.099Z	INFO	mc-server-runner	Done

**Comment by itzg** [comment] 2021-03-11 21:50
I'm still not sure you're running the copy of the compose file you intended. Make sure to save your changes perhaps.

I used exactly this file:
```yaml
version: "3"

services:
  
  minecraft-forge:
        container_name: minecraft-forge
        image: itzg/minecraft-server:java8
        restart: unless-stopped
        ports:
            - 25569:25565/tcp
        volumes:
            - './minecraft/forge:/data'
        environment:
            EULA: 'TRUE'
            #TYPE: 'CUSTOM'
            #CUSTOM_SERVER: 'forge-1.16.5-36.0.43.jar'
            #GUI: 'FALSE'
            TYPE: 'FORGE'
            VERSION: '1.16.5'
            FORGEVERSION: '36.0.43'
            FORGE_INSTALLER: 'forge-installer.jar'
            DEBUG_EXEC: 'TRUE'
```

and not surprisingly got the following error because I don't have a `forge-installer.jar`. Remove that file from your local environment since it is invalidating the scenario.

```
> docker-compose up
Creating network "issue799_default" with the default driver
Creating minecraft-forge ... done
Attaching to minecraft-forge
minecraft-forge    | [init] Changing ownership of /data to 1000 ...
minecraft-forge    | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    1 1000     1000           512 Mar 11 21:47 /data'
minecraft-forge    | [init] Resolved version given 1.16.5 into 1.16.5
minecraft-forge    | [init] Resolving type given FORGE
minecraft-forge    | [init] ERROR: the given Forge installer doesn't exist : forge-installer.jar
```

**Comment by itzg** [comment] 2021-03-11 21:52
Also remove the hidden file `minecraft/forge/.forge-installed-1.16.5` to force a new install.

**Comment by OverclockedSanic** [comment] 2021-03-11 22:01
Removing `.forge-installed` and `.forge-installed-1.16.5-36.0.43` had no effect.

With all due respect, `forge-installer.jar` does not invalidate the scenario; according to the readme, I should be able to use pre-downloaded installers:

> To use a pre-downloaded Forge installer, place it in the attached /data directory and specify the name of the installer file with FORGE_INSTALLER [...]

I would argue that instead of me removing the file, you should download the file from `https://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.0.43/forge-1.16.5-36.0.43-installer.jar`, rename it to `forge-installer.jar`, and add it to `/data`. Unless I'm completely misunderstanding the point of this option.

**Comment by OverclockedSanic** [comment] 2021-03-11 22:08
And yes, I am sure that this is the correct compose file. I've been commenting and uncommenting the environment variables for an hour now. every time it's set up as a custom server, it works (doesn't auto install the latest version tho) and every time it's set up as a forge server with an installer specified, it doesn't work.

**Comment by itzg** [comment] 2021-03-11 22:37
> I would argue that instead of me removing the file, you should download the file from `https://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.0.43/forge-1.16.5-36.0.43-installer.jar`, rename it to `forge-installer.jar`, and add it to `/data`. Unless I'm completely misunderstanding the point of this option.

That's  what this step of the startup script does when the file specified by `FORGE_INSTALLER` is not present:

https://github.com/itzg/docker-minecraft-server/blob/3c77abbbab2df9c86d24a542321434e9fd909046/start-deployForge#L60-L71

This line from your output is confusing me:

```
+ exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-installer.jar
```

since `forge-installer.jar` there would come from `$SERVER`, which in turn should come from `$CUSTOM_SERVER`. That bit of your compose file is:

```yaml
            #CUSTOM_SERVER: 'forge-1.16.5-36.0.43.jar'
            FORGE_INSTALLER: 'forge-installer.jar'
```

so it looks like `$FORGE_INSTALLER` showed up in there somehow.

To help me debug if the script is not doing what I expect, please `docker-compose pull` the latest image where I have added more debug output and add

```yaml
   DEBUG; "true"
```

If you can provide that output I can hopefully trace where the variables are getting mixed up.

**Comment by OverclockedSanic** [comment] 2021-03-11 22:49
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x   14 1000     1000            33 Mar 11 22:44 /data'
    [init] Resolved version given 1.16.5 into 1.16.5
    [init] Resolving type given FORGE
    + : world
    + export LEVEL
    + '[' FORGE = FEED-THE-BEAST ']'
    + worldDest=/data/world
    + [[ -n '' ]]
    + exec /start-finalSetupModpack
    + CURSE_URL_BASE=https://minecraft.curseforge.com/projects
    + isTrue
    + local value=
    + result=
    + case ${value} in
    + result=1
    + return 1
    + [[ -n '' ]]
    + [[ -n '' ]]
    + [[ -n '' ]]
    + [[ -n '' ]]
    + exec /start-finalSetupModconfig
    + '[' -d /plugins ']'
    + '[' -d /mods ']'
    + : /data/config
    + '[' -d /config ']'
    + exec /start-finalSetupServerProperties
    [init] server.properties already created, skipping
    [init] DEBUG Dumping server.properties
    #Minecraft server properties
    #Thu Mar 11 22:13:10 GMT 2021
    allow-flight=true
    allow-nether=true
    broadcast-console-to-ops=true
    broadcast-rcon-to-ops=true
    debug=false
    difficulty=easy
    enable-command-block=true
    enable-jmx-monitoring=false
    enable-query=false
    enable-rcon=false
    enable-status=true
    enforce-whitelist=true
    entity-broadcast-range-percentage=100
    force-gamemode=false
    function-permission-level=2
    gamemode=survival
    generate-structures=true
    generator-settings=
    hardcore=false
    level-name=world
    level-seed=-6149897779321282928
    level-type=largebiomes
    max-build-height=256
    max-players=5
    max-tick-time=60000
    max-world-size=29999984
    motd=SampleText
    network-compression-threshold=256
    online-mode=false
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp=true
    query.port=25565
    rate-limit=0
    rcon.password=minecraft
    rcon.port=25575
    resource-pack=
    resource-pack-sha1=
    server-ip=
    server-port=25565
    snooper-enabled=false
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    spawn-protection=0
    sync-chunk-writes=true
    text-filtering-config=
    texture-pack=
    use-native-transport=true
    view-distance=10
    white-list=true
    [init] log4j2.xml already created, skipping
    [init] Checking for JSON files.
    [init] Setting initial memory to 1G and max to 1G
    [init] Starting the Minecraft server...
    + exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-installer.jar nogui
    JVM info: IcedTea - 1.8.0_212 - 25.275-b01
    java.net.preferIPv4Stack=true
    Found java version 1.8.0_212
    Exception in thread "main" 
    java.awt.HeadlessException: 
    No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	    at java.awt.Window.<init>(Window.java:536)
	    at java.awt.Frame.<init>(Frame.java:420)
	    at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:408)
	    at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:170)
	    at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:143)
    2021-03-11T22:45:07.440Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
    2021-03-11T22:45:07.440Z	INFO	mc-server-runner	Done


compose file:

    minecraft-forge:
            container_name: minecraft-forge
            image: itzg/minecraft-server:java8
            restart: unless-stopped
            ports:
                - 25569:25565/tcp
            networks:
                - bungeecord_forge
            volumes:
                - './minecraft/forge:/data'
            environment:
                EULA: 'TRUE'
                #TYPE: 'CUSTOM'
                #CUSTOM_SERVER: 'forge-1.16.5-36.0.43.jar'
                GUI: 'FALSE'
                TYPE: 'FORGE'
                VERSION: '1.16.5'
                FORGEVERSION: '36.0.43'
                FORGE_INSTALLER: 'forge-installer.jar'
                DEBUG_EXEC: 'TRUE'
                DEBUG: 'TRUE'

**Comment by itzg** [comment] 2021-03-11 23:37
I'm sorry, I missed that you're using the `java8` tag. I have now merged the DEBUG change over, so please pull one more time and provide the output with that.

**Comment by OverclockedSanic** [comment] 2021-03-11 23:42
[Pastebin](https://pastebin.com/kmKveDnq)

**Comment by itzg** [comment] 2021-03-12 01:44
Thanks, that helped a bunch. I fixed a couple of bugs I found from that and pushed a new `itzg/minecraft-server:java8` image. See if that image fixes it for you.

**Comment by OverclockedSanic** [comment] 2021-03-12 06:57
Yup, that seems to have fixed most of it! The only issue I had after that was it still tried to run the pre-downloaded installer (in gui mode) when I removed `FORGEINSTALLER` from the environment variables (even when I also removed the installer JAR itself), but removing all the `.forge-installed*` files fixed that too.

**Closed** 2021-03-12 07:08 UTC
Labels: cannot confirm

**Comment by 19wolf** [comment] 2021-06-22 01:50
Hi, wasn't sure if I should start a new issue- I'm having this problem.

[Compose](https://pastebin.com/a9D8C6Uh)

[Debug output](https://pastebin.com/q40jhsiB)

**Comment by itzg** [comment] 2021-06-22 12:24
@19wolf yes, open a new issue
