### ISSUE TITLE
AUTOSTOP fails to trigger with TYPE=PAPER

### ISSUE THREAD

**Issue by Zazsona** [itzg/docker-minecraft-server#2572] opened 2024-01-02 01:52 UTC
### Describe the problem

Running under Paper build 365 and the latest image for itzg/minecraft-server (as of 2024-01-02!), I've noticed the Autostop functionality no longer seems to trigger. There are no errors in the log at start-up, or at the expected times when the server should be stopping.

mc-health returns:
`failed to ping localhost:25565 : json: cannot unmarshal string into Go struct field ServerInfo.description of type mcpinger.RegularChatComponent`

I'm wondering if this could be similar to #2545 as my container also reports as unhealthy, but figured I'd raise a separate issue in case I'm wrong in that assumption!

### Container definition

```
version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: TRUE
      USE_AIKAR_FLAGS: TRUE
      TYPE: PAPER
      PAPER_BUILD: 365
      ENABLE_AUTOSTOP: TRUE
      AUTOSTOP_TIMEOUT_EST: 1800
      AUTOSTOP_TIMEOUT_INIT: 900
    restart: "no"
    tty: true
    stdin_open: true
    volumes:
      - '../data/minecraft:/data'
```

### Container logs

```
[init] Autostop functionality enabled
[init] Resolving type given PAPER
[mc-image-helper] 01:11:04.287 INFO  : Resolved paper to version 1.20.4 build 365
[mc-image-helper] 01:11:14.068 INFO  : Created/updated 1 property in /data/server.properties
[init] Using Aikar's flags
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
```

**Comment by Zazsona** [comment] 2024-01-02 02:35
Bingo! - Applying [mnonke's suggestion](https://github.com/itzg/docker-minecraft-server/issues/2545#issuecomment-1868612203) and removing all instances of `§r` from the MOTD seems to have done the trick - Very likely it is just another symptom of the same issue!

My MOTD is defined directly in server.properties, and the `§r`s were within the string (i.e, not at the start or end), if that helps with any attempts to determine the root cause!

**Comment by itzg** [comment] 2024-01-02 03:26
Thanks for confirming the symptoms. Can we close since it definitely sounds like a duplicate of the same thing?

**Closed** 2024-01-02 12:04 UTC
Labels: bug, status/needs triage
