### ISSUE TITLE
Plugin (EssentialsX) unable to download when using SPIGET_RESOURCES

### ISSUE THREAD

**Issue by Crumb5** [itzg/docker-minecraft-server#1154] opened 2021-12-03 10:08 UTC
### Describe the problem

I get an error pertaining to the EssentialsX plugin when using the SPIGET_RESOURCES environment variable.

The few other plugins I've tested with seem to work fine, not sure if this is an issue with plugin or the way downloading/extracting plugins is handled.

Let me know if i can provide any other info. Thanks for reading :)

Console excerpt:
```
[init] Downloading PaperMC 1.17.1 (build 391) ...
[init] Getting plugins via Spiget
[init] Downloading resource 9089 ...
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/9089.zip or
        /tmp/9089.zip.zip, and cannot find /tmp/9089.zip.ZIP, period.
[init] Moving resource 9089 into plugins
[init] Downloading resource 34315 ...
[init] Moving resource 34315 into plugins
[init] Downloading resource 28140 ...
[init] Moving resource 28140 into plugins

[...Truncated...]

[09:57:04 ERROR]: Could not load 'plugins/9089.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.17.1.jar:git-Paper-391]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[patched_1.17.1.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-391]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-391]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-391]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.17.1.jar:git-Paper-391]
        ... 6 more

```

### Container definition

```
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc_test
    stdin_open: true
    tty: true 
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.17.1"
      EXEC_DIRECTLY: "TRUE"
      DIFFICULTY: hard
      USE_AIKAR_FLAGS: "TRUE"
      CONSOLE: "TRUE"
      SPIGET_RESOURCES: 9089,34315,28140

    ports:
      - 25565:25565
    volumes:
      - mc-paper:/data
    networks:
      - minecraft
      
networks:
  minecraft:
    name: mc_network
  
volumes:
  mc-paper:
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment] 2021-12-03 13:04
Duplicate of #1128

**Closed** 2021-12-03 13:04 UTC
Labels: bug, status/needs triage
