### ISSUE TITLE
Pufferfish Modrinth Downloader

### ISSUE THREAD

**Issue by Rattlyy** [itzg/docker-minecraft-server#2187] opened 2023-06-06 21:37 UTC
### Describe the problem

If you try to download plugins from Modrinth while using Pufferfish you will get an error.

### Container definition

```
creative:
    container_name: "creative"
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    volumes:
      - "./creative:/data"

    environment:
      EULA: "TRUE"
      TYPE: "PUFFERFISH"
      FORCE_REDOWNLOAD: true
      USE_FLARE_FLAGS: true
      USE_AIKAR_FLAGS: true
      SERVER_NAME: "creative"
      VERSION: "1.19.4"
      MEMORY: "10G"
      MODRINTH_PROJECTS: "luckperms,chunky"
      SPIGET_RESOURCES: "13449,390"

```

### Container logs

```
experimental  | Invalid value for option '--loader': expected one of [fabric, quilt, forge, bukkit, spigot, paper, purpur] (case-insensitive) but was 'pufferfish'
experimental  | Usage: mc-image-helper modrinth [--download-optional-dependencies]
experimental  |                                 [--allowed-version-type=<defaultVersionType>]
experimental  |                                 --game-version=<gameVersion> --loader=<loader>
experimental  |                                 [--output-directory=DIR] [--projects=id|slug
experimental  |                                 [\s*,\s*id|slug...]]...
experimental  | Automates downloading of modrinth resources
experimental  |       --allowed-version-type=<defaultVersionType>
experimental  |                           Valid values: release, beta, alpha
experimental  |       --download-optional-dependencies
experimental  |
experimental  |       --game-version=<gameVersion>
experimental  |                           Applicable Minecraft version
experimental  |       --loader=<loader>   Valid values: fabric, quilt, forge, bukkit, spigot,
experimental  |                             paper, purpur
experimental  |       --output-directory=DIR
experimental  |
experimental  |       --projects=id|slug[\s*,\s*id|slug...]
experimental  |                           Project ID or Slug
experimental exited with code 0
```

**Comment by itzg** [comment] 2023-06-07 12:48
[Purpur](https://purpurmc.org/) was the example I meant to share in Discord. These are the only plugin loaders that Modrinth can allow searching for

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/fef2f758-2388-4a6d-b414-f3b5a68ac570)

So, I just want to clarify that I will need to treat Pufferfish as "paper" when querying Modrinth.

**Comment by AliciaBurrito** [comment] 2023-09-05 00:00
Wanted to +1 this, as while I am using Purpur I have to manually manage or use Spiget instead for plugins that don't label themselves as Purpur compatible. 

Having an env variable or similar to allow querying for another loader would be immensely helpful for plugin management :)

**Comment by itzg** [comment] 2023-09-05 01:40
@AliciaBurrito thanks reviving this. It kept getting bumped by distractions. 

What's an example of a plugin that you would use with Purpur but declares as only Paper?

**Comment by AliciaBurrito** [comment] 2023-09-06 07:10
@itzg Haha no worries, I feel that :)

Here's a list of some plugins that I use on my own server that I need to manage outside of Modrinth exclusively to using Purpur:
- [ClickVillagers](https://modrinth.com/plugin/clickvillagers)
- [Player Carry](https://modrinth.com/plugin/carry/)
- [Teak's Tweaks](https://modrinth.com/plugin/teaks-tweaks)
- [ArcaneTable](https://modrinth.com/plugin/arcanetable)
- [Mobi's Homes](https://modrinth.com/plugin/mobis-homes)

This was particularly noticeably since I started off with a Paper server, but wanted to migrate to Purpur and hit a few roadblocks.

**Comment by itzg** [comment] 2023-09-06 12:29
I started making the code changes for this (including Pufferfish support) and was surprisingly easy thanks to Modrinth's API. The last bit I'd like to manually test is a plugin that has a Purpur specific version -- wanting to make sure that gets picked up rather than a Paper or Spigot version of the same. Do you happen to know of one?

**Comment by itzg** [comment] 2023-09-07 03:03
The latest image should now resolve this, but let me know if it doesn't in any cases.

**Comment by AliciaBurrito** [comment] 2023-09-07 18:54
@itzg I've noticed a possible regression from this change, it seems it's parsing the `MODRINTH_PROJECTS` differently(?) I have the following added to the `MODRINTH_PROJECTS` `female-gender-spigot` and it seems to almost double parse it now. One for `female-gender` and another for the intended `female-gender-spigot`. The former is a Fabric / Forge mod and errors out. You can see that happening below. 

`bcOsQHnC` is for the `female-gender` Fabric / Forge mod for context, while the intended plugin's project ID is `jDV9a8dQ`. Entering the project ID manually for the plugin also doesn't seem to work oddly enough, and is still trying to pull in the mod.

```
[mc-image-helper] 18:35:07.035 INFO  : Downloading Female-Gender-Mod-Spigot-1.0-SNAPSHOT.jar
[mc-image-helper] 18:35:07.100 ERROR : Invalid parameter provided for 'modrinth' command: No files are available for the project bcOsQHnC for loader purpur and Minecraft version 1.20.1
```

[Plugin](https://modrinth.com/plugin/female-gender-spigot)
[Mod](https://modrinth.com/mod/female-gender)

This only started after I restarted the server to pull the latest image. Let me know if this is unrelated and I can send in a new issue :)

**Comment by itzg** [comment] 2023-09-07 22:38
Thanks for the followup and the details. It may or may not be related and is likely a regression. I'll just reopen this issue and work it here.

**Comment by itzg** [comment] 2023-09-07 23:03
Actually...something is strange with that plugin's metadata. The plugin file's dependency points to the mod:

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/acdae809-683b-4d4a-b955-38c9ec075ea1)

With #2356 , which I think I'll start working on now, it will become possible to disable downloading of any dependencies.

I'll re-close this issue since the only fix I can do on my end is provide that option.

**Closed by itzg** 2023-09-07 23:03 UTC
Labels: enhancement

**Comment by itzg** [comment] 2023-09-09 14:08
The latest image should now fix that @AliciaBurrito
