### ISSUE TITLE
Unable to use the Send-Command flag

### ISSUE THREAD

**Issue by vanimox** [itzg/docker-minecraft-server#2990] opened 2024-07-14 09:48 UTC
### Describe the problem

After running `docker exec Minecraft123 send-command "say Hello, world!"` I get the following error: 

```
find: '/proc/1/exe': Permission denied
find: '/proc/12/exe': Permission denied
find: '/proc/42/exe': Permission denied
ERROR: failed to search for bedrock server process
```

### Container definition

```
Paste run command or compose file here
```version: '3'

services:
  minecraft-123-bedrock:
    image: itzg/minecraft-bedrock-server:latest
    container_name: Minecraft123
    environment:
      - EULA=TRUE
      - PUID=1000
      - PGID=1000
    ports:
      - "19132:19132/udp"
    volumes:
      - /docker/Minecraft123/data:/data
    restart: unless-stopped


### Container logs

find: '/proc/1/exe': Permission denied
find: '/proc/12/exe': Permission denied
find: '/proc/42/exe': Permission denied
ERROR: failed to search for bedrock server process

**Comment by itzg** [comment] 2024-07-14 12:45
This is reported in the wrong repo and seems to be a duplicate of https://github.com/itzg/docker-minecraft-bedrock-server/issues/334

**Closed by itzg** 2024-07-14 12:45 UTC
Labels: bug, status/needs triage
