### ISSUE TITLE
Latest FTB Modpacks wont work with type FTB

### ISSUE THREAD

**Issue by Janl1** [itzg/docker-minecraft-server#524] opened 2020-05-09 09:37 UTC
Today i tried to setup a minecraft server running with FTB Omnia modpack which is apparently quite new.
I found out that Feed The Beast must have changed their way of supplying server files.
They no longer use the large zip file which could be used with the FTB_SERVER_MOD parameter, but instead link a binary file ( https://api.modpacks.ch/public/modpack/6/50/server/linux ) in the FTB App which installs the entire server.

Is there a way to use this kind of flow inside the container?

<img width="1221" alt="Bildschirmfoto 2020-05-09 um 11 35 02" src="https://user-images.githubusercontent.com/12115859/81470110-31f88700-91e9-11ea-8465-83a83e3e9f27.png">

**Comment by itzg** [comment] 2020-05-09 21:49
Yes, CurseForge/FTB seem to continually find ways to inadvertently work against server automation systems like this image. I'll have to do some further research, but please keep me updated if you find any way to adapt with their new setup.

**Comment by jamierocks** [comment] 2020-05-19 23:05
> CurseForge/FTB

[Feed The Beast and Curse have parted ways](https://www.reddit.com/r/feedthebeast/comments/df2b0l/on_the_31st_october_2019_the_partnership_between/), as Curse did not renew their agreement. CreeperHost are effectively the Curse replacement, with their [modpacks.ch](https://modpacksch.docs.apiary.io/) service.

While it is frustrating that there aren't archives to download, their API is documented.

**Comment by jamierocks** [comment] 2020-05-19 23:08
If it is any help, I've written an open-source installer for modpacks from the modpacks.ch service - [ftbinstall](https://github.com/jamiemansfield/ftbinstall). I'm still working on it - but it is pretty good for FTB packs at the moment.

The only downside (in a sense) is that it (currently) uses my Neptune FTB Meta Service (which allows the installer to use pack slugs rather than IDs) - though I'm planning to just use their API direct.

**Comment by itzg** [comment] 2020-05-20 11:57
Thank you @jamierocks for the information about that situation. I had no idea what all was going on there. Whatever help you could provide for leveraging that new API would be fantastic.

**Comment by Rushmead** [comment] 2020-05-22 01:03
o/ As someone who worked and still works on the new FTB App and the modpacks.ch platform, if you have any questions feel free to ask :)

**Comment by itzg** [comment] 2020-05-22 02:01
Thanks @Rushmead ! I feel like I have been "fighting" against CurseForge to keep the server support going, so it's a relief to have a platform with a proper API.

**Comment by itzg** [comment] 2020-05-22 02:21
... @Rushmead now I see what @jamierocks meant. It would be nice to see the modpack ID In the FTB client so that users could plug that into this image's environment variables. Then the container startup could auto install the specific modpack with that ID.

Speaking of which, the linux server installer provided by [this API call](https://modpacksch.docs.apiary.io/#/reference/0/modpacks/linux-server-pack-installer-binary/200?mc=reference%2F0%2Fmodpacks%2Flinux-server-pack-installer-binary%2F200) looks extremely helpful, but I'm not sure why a modpack ID (6 in this case) is needed since it then allows for installing any modpack at invocation:

```
Usage:
ftb-installer - Start an interactive download and install.
ftb-installer searchterm - Search for a modpack and start interactive download and install.
ftb-installer <packid> - Download and install the latest Release version of a modpack by id.
ftb-installer <packid> <versionid> - Download and install a specific version of a modpack by id and version id.

Additional arguments:
--help - Print this help information.
--path - Specify an install path instead of current working directory.
--auto - Automatically install a pack for filename based pack installs.
--noscript - Don't generate start.sh and start.bat files.
--latest - Ignore any specific modpack version id provided and always download the latest.
```

Thanks and I can jump on your Discord server and chat there if you prefer.

**Comment by jamierocks** [comment] 2020-05-22 02:27
The installer provided by CreeperHost is just the same file as far as I'm aware, using its `Content-Disposition` name to determine what the pack and version is.

The easiest way to view IDs at the moment is with https://ftb.neptunepowered.org/, but it would be nice to grab them from the app for those that use it.

**Comment by itzg** [comment] 2020-05-22 03:22
Oh, the linux installer doesn't support Alpine/musl :

```
bash-4.4# strace ./ftb-installer 
execve("./ftb-installer", ["./ftb-installer"], 0x7fff6693d210 /* 38 vars */) = 0
open("/proc/self/exe", O_RDONLY)        = 3
mmap(NULL, 9331806, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe9a4df8000
mmap(0x7fe9a4df8000, 9331381, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x7fe9a4df8000
mprotect(0x7fe9a56dd000, 5214, PROT_READ|PROT_EXEC) = 0
readlink("/proc/self/exe", "/data/ftb-installer", 4095) = 19
mmap(0x400000, 31703040, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x400000
mmap(0x400000, 29574820, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x400000
mprotect(0x400000, 29574820, PROT_READ|PROT_EXEC) = 0
mmap(0x2234000, 28448, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0x1c34000) = 0x2234000
mprotect(0x2234000, 28448, PROT_READ|PROT_WRITE) = 0
mmap(0x223b000, 816, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x223b000
open("/lib64/ld-linux-x86-64.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
```

I'll have to initially add support only to the multiarch branch, which is based on ubuntu rather than alpine.

**Comment by itzg** [comment] 2020-05-22 03:49
I have pushed a test image which includes support for a new `TYPE=FTBA`:

```
docker run -it --rm -e EULA=TRUE -e TYPE=FTBA -e FTB_MODPACK_ID=6 itzg/minecraft-server:multiarch-test
```

A specific modpack version ID can also be supplied with `FTB_MODPACK_VERSION_ID`

**Comment by itzg** [comment] 2020-05-29 21:31
You found one of the rough edges ;) I'll do some debugging and fixes with that modpack ID.

**Comment by rclabough** [comment] 2020-05-29 21:42
Always happy to break things!  Let me know if you need me to try it again with a new image

**Comment by itzg** [comment] 2020-05-29 22:48
@rclabough if you could re-pull `itzg/minecraft-server:multiarch-test` let's see if that fixed it for you too. I needed to tweak the support for Forge 1.7.10 jar file naming. Your output was a little different than mine when it failed, so if you still have issues, please add `DEBUG: "TRUE"` and that'll give me some more details to work from.

**Comment by rclabough** [comment] 2020-05-29 22:58
Done, and done.  Unfortunately still erroring.  I've attached the full debug output here.

[minecraft_debug.txt](https://github.com/itzg/docker-minecraft-server/files/4704707/minecraft_debug.txt)

**Comment by rclabough** [comment] 2020-05-29 23:00
[minecraft_debug.txt](https://github.com/itzg/docker-minecraft-server/files/4704716/minecraft_debug.txt)

Done and done.  Unfortunately still erroring with code 0.  Attached the full debug output here.

**Comment by itzg** [comment] 2020-05-30 01:34
Ah, so it failed within the modpack loading? (I'm too impatient for modpacks, so I didn't let it load that far.)

It fails here, but...
```
[34mminecraft_1         |[0m [15:52:49] [Server thread/ERROR]: PneumaticCraft wasn't able to load third party content from the third party class class pneumaticCraft.common.thirdparty.NotEnoughKeys in the PreInit phase!
[34mminecraft_1         |[0m [15:52:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoClassDefFoundError: modwarriors/notenoughkeys/api/KeyBindingPressedEvent
[34mminecraft_1         |[0m [15:52:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
```

I'm actually wondering if the healthcheck is failing at that point since I think it allows about 2 minutes by default. You could increase the retries like so

https://docs.docker.com/compose/compose-file/#healthcheck

**Comment by rclabough** [comment] 2020-05-30 02:41
Well, that forced me to finally upgrade my docker compose to 3.8, but no cigar unfortunately.  Ends with the same:
```
minecraft_1         | [19:30:47] [Server thread/INFO]: Constructing submodule info.inpureprojects.core.Preloader.ModulePreloader
minecraft_1         | [19:30:47] [Server thread/INFO]: Constructing submodule info.inpureprojects.core.Scripting.ScriptExtractor
minecraft_1         | [19:30:47] [Server thread/INFO]: Processing preinit event for submodule info.inpureprojects.core.Preloader.ModulePreloader
minecraft_1         | [19:30:47] [Server thread/INFO]: Processing preinit event for submodule info.inpureprojects.core.Scripting.ScriptExtractor
minecraft_1         | [19:30:47] [Server thread/INFO]: Loading configuration
minecraft_1         | [19:30:47] [Server thread/INFO]: Wrong side: SERVER, Developer Tools Addon not loading
minecraft_1         | [19:30:47] [Server thread/INFO]: Version check success: appliedenergistics2 required / rv2-stable-10 detected
minecraft_1         | [19:30:47] [Server thread/INFO]: Wrong side: SERVER, Botany Addon not loading
minecraft_1         | [19:30:47] [Server thread/INFO]: Version check success: Forestry@[2.2.9.0,) required / 3.6.3.20 detected
minecraft_1         | [19:30:47] [Server thread/INFO]: Wrong side: SERVER, Crafting Tables Addon not loading
minecraft_1         | [19:30:47] [Server thread/INFO]: Wrong side: SERVER, Ex Nihilo Addon not loading
minecraft_1         | [19:30:47] [Server thread/INFO]: Config loaded from: /data/config/ObsidiPlates.cfg
minecraft_1         | [19:30:48] [Server thread/INFO]: InvTweaks: net.minecraft.inventory.ContainerPlayer
minecraft_1         | [19:30:49] [Server thread/WARN]: Failed on getting Forestry's farm blocks, using defaults
minecraft_1         | [19:30:49] [Server thread/ERROR]: PneumaticCraft wasn't able to load third party content from the third party class class pneumaticCraft.common.thirdparty.NotEnoughKeys in the PreInit phase!
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoClassDefFoundError: modwarriors/notenoughkeys/api/KeyBindingPressedEvent
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.Class.getDeclaredMethods0(Native Method)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.Class.privateGetPublicMethods(Class.java:2902)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.Class.getMethods(Class.java:1615)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:60)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at pneumaticCraft.common.thirdparty.NotEnoughKeys.preInit(NotEnoughKeys.java:14)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at pneumaticCraft.common.thirdparty.ThirdPartyManager.preInit(ThirdPartyManager.java:111)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at pneumaticCraft.PneumaticCraft.PreInit(PneumaticCraft.java:97)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.reflect.Method.invoke(Method.java:498)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.reflect.Method.invoke(Method.java:498)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.reflect.Method.invoke(Method.java:498)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ClassNotFoundException: modwarriors.notenoughkeys.api.KeyBindingPressedEvent
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    ... 39 more
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.RuntimeException: Attempted to load class modwarriors/notenoughkeys/api/KeyBindingPressedEvent for invalid side SERVER
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
minecraft_1         | [19:30:49] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]:    ... 41 more
minecraft_1         | [19:30:49] [Server thread/INFO]: [4.0.0-beta-6] Loading properties.
minecraft_1         | [19:30:50] [Server thread/WARN]: Failed to load PR Plugin: Treecapitator gem axe compatibility
minecraft_1         | [19:30:50] [Server thread/WARN]: Failed to load PR Plugin: CPT Colored Lights Compat for Illumination lighting
minecraft_1         | [19:30:50] [Server thread/WARN]: Failed to load PR Plugin: Deep Storage Unit pipe interactions
minecraft_1         | [19:30:50] [Server thread/INFO]: Could not read 'userbuilder.json', this is not an error!
minecraft_1         | [19:30:51] [Server thread/INFO]: Loading configuration...
minecraft_1         | [19:30:51] [Server thread/INFO]: Done.
minecraft_1         | [19:30:51] [CoFHUpdater:ThermalDynamics/ERROR]: Update check for Thermal Dynamics failed.
minecraft_1         | java.io.FileNotFoundException: https://raw.githubusercontent.com/CoFH/VERSION/master/ThermalDynamics
minecraft_1         |   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896) ~[?:1.8.0_252]
minecraft_1         |   at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_252]
minecraft_1         |   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490) ~[?:1.8.0_252]
minecraft_1         |   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488) ~[?:1.8.0_252]
minecraft_1         |   at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
minecraft_1         |   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_252]
minecraft_1         |   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487) ~[?:1.8.0_252]
minecraft_1         |   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_252]
minecraft_1         |   at java.net.URL.openStream(URL.java:1068) ~[?:1.8.0_252]
minecraft_1         |   at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:44) [UpdateCheckThread.class:?]
minecraft_1         | [19:30:52] [Server thread/INFO]: Applying holder lookups
minecraft_1         | [19:30:52] [Server thread/INFO]: Holder lookups applied
minecraft_1         | [19:30:52] [Server thread/INFO]: Injecting itemstacks
minecraft_1         | [19:30:52] [Server thread/INFO]: Itemstack injection complete
minecraft_1         | [19:30:52] [Server thread/INFO]: Loading properties
minecraft_1         | [19:30:52] [Server thread/INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.
minecraft_1         | [19:30:52] [Server thread/WARN]: Can't revert to frozen GameData state without freezing first.
minecraft_1         | [19:30:52] [Server thread/INFO]: Applying holder lookups
minecraft_1         | [19:30:52] [Server thread/INFO]: Holder lookups applied
minecraft_1         | [19:30:52] [Server thread/WARN]: Failed to write Transciever Channels on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException
minecraft_1         | [19:30:52] [Server thread/ERROR]: Skipping event FMLServerStoppedEvent and marking errored mod factorization.misc since required dependency factorization has errored
minecraft_1         | [19:30:52] [Server thread/ERROR]: Skipping event FMLServerStoppedEvent and marking errored mod HatStand since required dependency Hats has errored
minecraft_1         | [19:30:52] [Server thread/INFO]: RFTools: server is stopping. Shutting down gracefully
minecraft_1         | [19:30:52] [Server thread/INFO]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
minecraft_1         | [19:30:52] [Server thread/INFO]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
minecraft_1         | 2020-05-29T19:30:53.019-0700      INFO    mc-server-runner        Done
minecraft_1         | Exception in thread "AE2 VersionChecker" docker_minecraft_1 exited with code 0
```

With my new docker compose with a longer timeout:
```
 minecraft:
    image: itzg/minecraft-server:multiarch-test
    network_mode: host
    environment:
      TZ: "America/Los_Angeles"
      ENABLE_AUTOPAUSE: "TRUE"
      EULA: "TRUE"
      SERVER_PORT: 25565
      OPS: << my username >>
      MEMORY: "2G"
      GUI: "FALSE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: 14
      DEBUG: "TRUE"
    volumes:
     - /localdata/minecraft/data:/data
    ports:
     - 25565:25565
     - 19132:19132/udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25565"]
      interval: 1m30s
      timeout: 240s
      retries: 3
      start_period: 240s
```

**Comment by itzg** [comment] 2020-05-30 15:45
Yeah, it still looks like it's that mod issue:
```
minecraft_1         | [19:30:49] [Server thread/ERROR]: PneumaticCraft wasn't able to load third party content from the third party class class pneumaticCraft.common.thirdparty.NotEnoughKeys in the PreInit phase!
```

I tried the 1.12 version of the Direwolf20 modpack, `FTP_MODPACK_ID=31`, and it seemed to startup all the way.

**Comment by rclabough** [comment] 2020-05-30 18:06
Thank you for diving in so deep into that, and not even for your issue!  Interesting that that modpack couldn't start.  

Could I suggest an error message along the lines of `Error in starting/initializing FTB Modpack 14` or essentially just blatantly obvious that something failed initializing the mod, not the docker image.  I feel bad that I wasted your time and it ended up being the mod itself.

Was able to switch over and confirmed it makes it farther, but looks like one last error in the java jar initialization:
```
minecraft_1         | }[init] Creating server.properties in /data/server.properties
minecraft_1         | [init] Setting server-name to 'Dedicated Server' in /data/server.properties
minecraft_1         | [init] Skip setting server-ip
minecraft_1         | [init] Setting server-port to '25565' in /data/server.properties
minecraft_1         | [init] Setting motd to 'A Ftba Minecraft Server powered by Docker' in /data/server.properties
minecraft_1         | [init] Skip setting allow-nether
minecraft_1         | [init] Skip setting announce-player-achievements
minecraft_1         | [init] Skip setting enable-command-block
minecraft_1         | [init] Skip setting spawn-animals
minecraft_1         | [init] Skip setting spawn-monsters
minecraft_1         | [init] Skip setting spawn-npcs
minecraft_1         | [init] Skip setting spawn-protection
minecraft_1         | [init] Skip setting generate-structures
minecraft_1         | [init] Skip setting view-distance
minecraft_1         | [init] Skip setting hardcore
minecraft_1         | [init] Skip setting snooper-enabled
minecraft_1         | [init] Skip setting max-build-height
minecraft_1         | [init] Skip setting force-gamemode
minecraft_1         | [init] Skip setting max-tick-time
minecraft_1         | [init] Skip setting enable-query
minecraft_1         | [init] Skip setting query.port
minecraft_1         | [init] Setting enable-rcon to 'true' in /data/server.properties
minecraft_1         | [init] Setting rcon.password to 'minecraft' in /data/server.properties
minecraft_1         | [init] Setting rcon.port to '25575' in /data/server.properties
minecraft_1         | [init] Skip setting max-players
minecraft_1         | [init] Skip setting max-world-size
minecraft_1         | [init] Setting level-name to 'world' in /data/server.properties
minecraft_1         | [init] Skip setting level-seed
minecraft_1         | [init] Setting pvp to 'true' in /data/server.properties
minecraft_1         | [init] Skip setting generator-settings
minecraft_1         | [init] Setting online-mode to 'true' in /data/server.properties
minecraft_1         | [init] Skip setting allow-flight
minecraft_1         | [init] Setting level-type to 'DEFAULT' in /data/server.properties
minecraft_1         | [init] Skip setting resource-pack
minecraft_1         | [init] Skip setting resource-pack-sha1
minecraft_1         | [init] Skip setting player-idle-timeout
minecraft_1         | [init] Setting difficulty to 'easy' in /data/server.properties
minecraft_1         | [init] Setting/adding ops
minecraft_1         | [init] Creating log4j2.xml in /data/log4j2.xml
minecraft_1         | [init] Checking for JSON files.
minecraft_1         | [init] Setting initial memory to 8G and max to 8G
minecraft_1         | [init] Starting the Minecraft server...
minecraft_1         | Error: -jar requires jar file specification
minecraft_1         | Usage: java [-options] class [args...]
minecraft_1         |            (to execute a class)
minecraft_1         |    or  java [-options] -jar jarfile [args...]
minecraft_1         |            (to execute a jar file)
minecraft_1         | where options include:
minecraft_1         |     -d32    use a 32-bit data model if available
minecraft_1         |     -d64    use a 64-bit data model if available
minecraft_1         |     -server         to select the "server" VM
minecraft_1         |     -zero   to select the "zero" VM
minecraft_1         |     -dcevm          to select the "dcevm" VM
minecraft_1         |                   The default VM is server,
minecraft_1         |                   because you are running on a server-class machine.
minecraft_1         |
minecraft_1         |
minecraft_1         |     -cp <class search path of directories and zip/jar files>
minecraft_1         |     -classpath <class search path of directories and zip/jar files>
minecraft_1         |                   A : separated list of directories, JAR archives,
minecraft_1         |                   and ZIP archives to search for class files.
minecraft_1         |     -D<name>=<value>
minecraft_1         |                   set a system property
minecraft_1         |     -verbose:[class|gc|jni]
minecraft_1         |                   enable verbose output
minecraft_1         |     -version      print product version and exit
minecraft_1         |     -version:<value>
minecraft_1         |                   Warning: this feature is deprecated and will be removed
minecraft_1         |                   in a future release.
minecraft_1         |                   require the specified version to run
minecraft_1         |     -showversion  print product version and continue
minecraft_1         |     -jre-restrict-search | -no-jre-restrict-search
minecraft_1         |                   Warning: this feature is deprecated and will be removed
minecraft_1         |                   in a future release.
minecraft_1         |                   include/exclude user private JREs in the version search
minecraft_1         |     -? -help      print this help message
minecraft_1         |     -X            print help on non-standard options
minecraft_1         |     -ea[:<packagename>...|:<classname>]
minecraft_1         |     -enableassertions[:<packagename>...|:<classname>]
minecraft_1         |                   enable assertions with specified granularity
minecraft_1         |     -da[:<packagename>...|:<classname>]
minecraft_1         |     -disableassertions[:<packagename>...|:<classname>]
minecraft_1         |                   disable assertions with specified granularity
minecraft_1         |     -esa | -enablesystemassertions
minecraft_1         |                   enable system assertions
minecraft_1         |     -dsa | -disablesystemassertions
minecraft_1         |                   disable system assertions
minecraft_1         |     -agentlib:<libname>[=<options>]
minecraft_1         |                   load native agent library <libname>, e.g. -agentlib:hprof
minecraft_1         |                   see also, -agentlib:jdwp=help and -agentlib:hprof=help
minecraft_1         |     -agentpath:<pathname>[=<options>]
minecraft_1         |                   load native agent library by full pathname
minecraft_1         |     -javaagent:<jarpath>[=<options>]
minecraft_1         |                   load Java programming language agent, see java.lang.instrument
minecraft_1         |     -splash:<imagepath>
minecraft_1         |                   show splash screen with specified image
minecraft_1         | See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
minecraft_1         | 2020-05-30T11:03:57.611-0700      INFO    mc-server-runner        Done
```

I did have to alter my docker-compose a bit to get it that far.  The GUI: FALSE caused errors saying it couldn't access the nogui package, went away after removing that.  Also was limiting my memory usage while debugging, but was getting exit code 4s, also went away now that I've bumped up to 8.

**Comment by itzg** [comment] 2020-05-31 01:55
@rclabough don't feel bad at all. I'm actually not sure if I could have it detect the difference in failure to start, so we'll just have to leave for a debugging adventure.

As for your "-jar" error, that seems like a bug in my script somewhere....oh, did this happen on restarting the container? I actually don't think I have tested that yet 😬. Either way, I'll test out some more but can you also provide output with both `-e DEBUG=true -e DEBUB_EXEC=true`?

**Comment by itzg** [comment] 2020-05-31 13:44
I pushed an update of `itzg/minecraft-server:multiarch-test` that tracks the modpack and version installed to avoid the whole process on restart.

**Comment by rclabough** [comment] 2020-05-31 19:32
Hey, I don't know what happened but the last pull got it to work!  No Java error.  I built from scratch with no error and restarted with no error.  Was able to connect and everything appears functional!  

Thanks for all of your help, I'll be looking forward to this being merged into the mainline!

**Comment by itzg** [comment] 2020-05-31 22:50
Awesome. I’ll first be merging into the “multiarch” branch/tag, so that’ll be semi-mainline until I ponder if to just switch from alpine to Ubuntu for the master/latest mainline base image.

**Comment by itzg** [comment] 2020-05-31 23:42
This is now merged into the ` itzg/minecraft-server:multiarch` image and documented in the mainline README:

https://github.com/itzg/docker-minecraft-server#running-a-server-with-a-feed-the-beast-modpack

**Closed by itzg** 2020-05-31 23:42 UTC

**Comment by itzg** [comment] 2020-05-31 23:47
...and example compose file has been added

https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-ftba.yml
